puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Ruth Earle"
puts "Andy Gates"
puts "Marc Singh"
puts "Faisal Aydarus"
puts "Ethel Ng"
puts "Kevin Daniels"
puts "Maya Driver"
puts "Leopold Kwok"
puts "James McNeil"
puts "Jerome Pratt"
puts "David Wickes"
puts "Javier Silverio"
puts "Elliot Lewis"
puts "Ben Tillett"
puts "Vincent Koch"
puts "Michelle Ballard"
puts "Nick Roberts"
puts "Tatiana Soukiassian"
puts "Merve Silk"
puts "Albert Vallverdu"
puts "Loius Schultze"
puts "Chris Oatley"
puts "Spike Lindsey"
puts "Henry Stanley"
print "Overall, we have "
print 23
puts " great student"
